# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
         autowire: true
         autoconfigure: true

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{DependencyInjection,Entity,Migrations,Tests}'

    #app.control_user:
     # class: AppBundle\Security\UserControl
      #arguments: ['@security.authorization_checker', '@security.token_storage']